dist: xenial
language: python
python:  # https://devguide.python.org/#status-of-python-branches
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
env:  # https://www.djangoproject.com/download/
  - DJANGO=2.2.4 CRYPTOGRAPHY=2.7
  - DJANGO=2.2.4 CRYPTOGRAPHY=2.6.1
  - DJANGO=2.2.4 CRYPTOGRAPHY=2.5
  - DJANGO=2.1.11 CRYPTOGRAPHY=2.7
  - DJANGO=2.1.11 CRYPTOGRAPHY=2.6.1
  - DJANGO=2.1.11 CRYPTOGRAPHY=2.5
  - DJANGO=1.11.23 CRYPTOGRAPHY=2.7
  - DJANGO=1.11.23 CRYPTOGRAPHY=2.6.1
  - DJANGO=1.11.23 CRYPTOGRAPHY=2.5
install:
  # Build/test dependencies
 - pip install -U pip setuptools
 - pip install -r requirements/requirements-travis.txt
 - pip install Django==$DJANGO cryptography==$CRYPTOGRAPHY
#before_script:
script:
  # download selenium driver
  - mkdir -p contrib/selenium 
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar xf geckodriver-v0.24.0-linux64.tar.gz -C contrib/selenium

  - python dev.py code-quality
  - python dev.py coverage --format=text
  - echo -e "DEBUG = True\nSECRET_KEY = 'dummy'" > ca/ca/localsettings.py
  - python dev.py init-demo
  - python setup.py install
  - make -C docs html-check

matrix:
    exclude:
        # Django 2.2 no longer supports python2.7
          python: "2.7"
        - env: DJANGO=2.2.4 CRYPTOGRAPHY=2.7
          python: "2.7"
        - env: DJANGO=2.2.4 CRYPTOGRAPHY=2.6.1
          python: "2.7"
        - env: DJANGO=2.2.4 CRYPTOGRAPHY=2.5
          python: "2.7"

        # Django 2.1 no longer supports python2.7
          python: "2.7"
        - env: DJANGO=2.1.11 CRYPTOGRAPHY=2.7
          python: "2.7"
        - env: DJANGO=2.1.11 CRYPTOGRAPHY=2.6.1
          python: "2.7"
        - env: DJANGO=2.1.11 CRYPTOGRAPHY=2.5
          python: "2.7"

        # We do not test Django 1.11 with Python nightly
          python: "nightly"
        - env: DJANGO=1.11.23 CRYPTOGRAPHY=2.7
          python: "nightly"
        - env: DJANGO=1.11.23 CRYPTOGRAPHY=2.6.1
          python: "nightly"
        - env: DJANGO=1.11.23 CRYPTOGRAPHY=2.5
          python: "nightly"
