version: "3.7"
services:
    redis:
        image: redis:5-alpine
        ports:
            - "6379"
        networks:
            - cache
        restart: unless-stopped

    postgres:
        image: postgres:12-alpine
        environment:
            POSTGRES_DB:
            POSTGRES_PASSWORD:
            POSTGRES_USER:
        ports:
            - 5432:5432
        networks:
            - database
        restart: unless-stopped

    backend:
        image: mathiasertl/django-ca:latest
        command: ./celery.sh -l ${CELERY_LOG_LEVEL:-warning}
        depends_on:
            - redis
        networks:
            - cache
            - database
        volumes:
            - shared_ca_dir:/var/lib/django-ca/certs/ca/shared/
            - ocsp_key_dir:/var/lib/django-ca/certs/ocsp/
            - shared:/var/lib/django-ca/shared/
        environment:
            DJANGO_CA_SECRET_KEY: ${DJANGO_CA_SECRET_KEY:-}
            DJANGO_CA_SECRET_KEY_FILE: ${DJANGO_CA_SECRET_KEY_FILE:-/var/lib/django-ca/shared/secret-key}
            DJANGO_CA_HOSTNAME: ${DJANGO_CA_HOSTNAME:-localhost}
            DJANGO_CA_SETTINGS: settings.yaml:compose.yaml
            POSTGRES_DB:
            POSTGRES_PASSWORD:
            POSTGRES_USER:
        restart: unless-stopped
        stop_grace_period: 30s

    frontend:
        image: mathiasertl/django-ca:latest
        depends_on:
            - redis
            - postgres
        ports:
            - 8000:8000
        networks:
            - cache
            - database
            - frontend
        volumes:
            - static:/usr/share/django-ca/static/
            - shared_ca_dir:/var/lib/django-ca/certs/ca/shared/
            - ocsp_key_dir:/var/lib/django-ca/certs/ocsp/
            - shared:/var/lib/django-ca/shared/
        environment:
            DJANGO_CA_HOSTNAME: ${DJANGO_CA_HOSTNAME:-localhost}
            DJANGO_CA_SETTINGS: settings.yaml:compose.yaml
            DJANGO_CA_SECRET_KEY: ${DJANGO_CA_SECRET_KEY:-}
            DJANGO_CA_SECRET_KEY_FILE: ${DJANGO_CA_SECRET_KEY_FILE:-/var/lib/django-ca/shared/secret-key}
            DJANGO_CA_UWSGI_INI: /usr/src/django-ca/uwsgi/uwsgi.ini
            POSTGRES_DB:
            POSTGRES_PASSWORD:
            POSTGRES_USER:
        restart: unless-stopped
        stop_signal: SIGINT

    webserver:
        image: nginx:1.17-alpine
        environment:
            DJANGO_CA_HOSTNAME: ${DJANGO_CA_HOSTNAME:-localhost}
        ports:
            - 80:80
        networks:
            - frontend
            - public
        volumes:
            - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
            - static:/usr/share/nginx/html/static/

volumes:
    shared:
    static:
    shared_ca_dir:
    ocsp_key_dir:

networks:
    public:
    frontend:
        internal: true
    cache:
        internal: true
    database:
        internal: true
