version: "3.7"
services:
    redis:
        image: redis:5-alpine
        ports:
            - "6379"
        networks:
            - cache
        restart: unless-stopped
        deploy:
            restart_policy:
                condition: unless-stopped

    postgres:
        image: postgres:12-alpine
        ports:
            - 5432:5432
        networks:
            - database
        restart: unless-stopped
        deploy:
            restart_policy:
                condition: unless-stopped

    backend:
        image: mathiasertl/django-ca:latest
        command: celery worker -l debug -A ca
        working_dir: /usr/src/django-ca/ca
        networks:
            - cache
            - database
        volumes:
            - ${PWD}/${DJANGO_CA_SETTINGS:-/docker/settings.yaml}:/usr/src/django-ca/settings.yaml
        environment:
            DJANGO_CA_SETTINGS: ${DJANGO_CA_SETTINGS:-/usr/src/django-ca/settings.yaml}
        restart: unless-stopped
        deploy:
            restart_policy:
                condition: unless-stopped

    frontend:
        image: mathiasertl/django-ca:latest
        ports:
            - 8000:8000
        networks:
            - cache
            - database
            - frontend
        volumes:
            - ${PWD}/${DJANGO_CA_SETTINGS:-/docker/settings.yaml}:/usr/src/django-ca/settings.yaml
        environment:
            DJANGO_CA_SETTINGS: ${DJANGO_CA_SETTINGS:-/usr/src/django-ca/settings.yaml}
        restart: unless-stopped
        deploy:
            restart_policy:
                condition: unless-stopped

networks:
    frontend:
    cache:
        internal: true
    database:
        internal: true
