CACHES:
    default:
        BACKEND: redis_cache.RedisCache
        LOCATION: redis://redis:6379
        OPTIONS:
            DB: 1
            PARSER_CLASS: redis.connection.HiredisParser

DATABASES:
    default:
        ENGINE: django.db.backends.postgresql_psycopg2
        NAME: postgres
        USER: postgres
        PASSWORD: postgres
        HOST: postgres
        PORT: 5432
